name: Build and push Docker image
on:
  push:
    branches:
      - master

jobs:
  build_and_publish_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      run: |
        docker login -p ${{ secrets.DOCKER_PASSWORD }} -u ${{ secrets.DOCKER_USERNAME }}
        docker build -t yigitsadic/gocandela .
        docker push yigitsadic/gocandela
