# This is a basic workflow to help you get started with Actions

name: Run candela image

on:
  push:
    branches: [ master ]

jobs:
  run_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch image
      run: docker pull yigitsadic/gocandela

    - name: Run a one-line script
      run: docker run --rm yigitsadic/gocandela > earthquakes.json

    - name: Save earthquakes.json file to the repository
      run: |
        git config --global user.email "yigitsadic@gmail.com"
        git config --global user.name "Yigit Sadic"
        git commit -am "Routine file update."
        git push
