# This is a basic workflow to help you get started with Actions

name: Run candela image

on:
  push:
    branches: [ master ]

jobs:
  run_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Fetch image
      run: docker pull yigitsadic/gocandela

    - name: Run a one-line script
      run: docker run --rm yigitsadic/gocandela
