# This is a basic workflow to help you get started with Actions

name: Run candela image

on:
  push:
    branches: [ master ]

jobs:
  run_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch image
      run: docker pull yigitsadic/gocandela

    - name: Run a one-line script
      run: docker run --rm yigitsadic/gocandela > earthquakes.json

    - uses: EndBug/add-and-commit@v4
      with:
        add: earthquakes.json
        message: "CRON earthquake commit."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
